from src.schema_graph.evaluator import SQLEvaluator
from src.schema_graph.models import EvaluationDetail


class AdapterEvaluator:
    """Evaluate SQL generated by an adapter-backed inference client."""

    def __init__(
        self,
        *,
        inference,
        sql_evaluator: SQLEvaluator | None = None,
    ):
        self.inference = inference
        self.sql_evaluator = sql_evaluator or SQLEvaluator()

    def evaluate(
        self,
        examples,
        *,
        prompt_builder,
    ) -> list[EvaluationDetail]:
        results = []

        for example in examples:
            prompt = prompt_builder(example.question)

            predicted_sql = self.inference.generate(prompt)

            results.append(
                EvaluationDetail(
                    question=example.question,
                    expected_sql=example.expected_sql,
                    predicted_sql=predicted_sql,
                    strict_match=self.sql_evaluator.evaluate(
                        predicted_sql=predicted_sql,
                        expected_sql=example.expected_sql,
                    ),
                    execution_match=False,
                )
            )

        return results